$engine: 3
$onesync: on

name: vMenu
author: Tom Grobbe
description: A FiveM server with vMenu v3.8.67 ready to go. A server sided trainer/menu with full permission support.

tasks:
  # Download default resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources

  # Remove the old chat resource
  - action: remove_path
    path: ./resources/[gameplay]/chat

  # Download server.cfg
  - action: download_file
    url: https://github.com/TomGrobbe/vMenu/releases/download/enhanced-v1.0.3/txadmin-files.zip
    path: ./tmp/txadmin-files.zip

  - action: unzip
    src: ./tmp/txadmin-files.zip
    dest: ./tmp/txadmin-files

  - action: move_path
    src: ./tmp/txadmin-files/txadmin-vmenu-legacy-server.cfg
    dest: ./server.cfg

  # Download vMenu, the folder name has to be exactly vMenu
  - action: download_file
    url: https://github.com/TomGrobbe/vMenu/releases/download/enhanced-v1.0.3/vMenu-3.8.67.zip
    path: ./tmp/vmenu.zip

  - action: unzip
    src: ./tmp/vmenu.zip
    dest: ./resources/vMenu

  # Clean up
  - action: remove_path
    path: ./tmp
