on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - run: |
          set -e

          release=$(curl -fsSL -H 'Authorization: Bearer ${{secrets.GITHUB_TOKEN}}' https://api.github.com/repos/TomGrobbe/vMenu/releases/latest)

          latest_url=$(jq -er '.assets[0].browser_download_url' <<< $release)

          current_url=$(yq -er '.tasks[] | select(.path == "./tmp/vmenu.zip") | .url' recipe.yaml)

          if [ "$current_url" = "$latest_url" ]; then exit; fi

          sed -i "s|$current_url|$latest_url|" recipe.yaml

          git config user.name "Yorick"

          git config user.email "admin@yorick.gg"

          git add recipe.yaml

          git commit -m "chore: Update vMenu" -q

          git push -q
